version: '3.8'
services: 
  keycloak:
    build:
      context: .
    ports: ["8080:8080"]
  ui:
    build:
      context: ui
    ports: ["8081:8081"]
    environment:
      CONFERENCE_API_URL: api:8082
    volumes:
      - "./ui:/ui"
  api:
    build:
      context: api
    ports: ["8082:8082"]
  mail:
    image: mailhog/mailhog
    ports:
    - "8025:8025"
    - "1025:1025"
