version: '3.8'
services: 
  keycloak:
    build:
      context: .
    ports: ["8080:8080", "8787:8787"]
    volumes:
      - "./keycloak-data:/import"
  ui:
    build:
      context: ui
    ports: ["8081:8081"]
    environment:
      CONFERENCE_API_URL: api:8082
      KEYCLOAK_BASE_URL: http://keycloak:8080/auth
      KEYCLOAK_REALM: blablaconf
      KEYCLOAK_CLIENT_ID: ui
      KEYCLOAK_CLIENT_SECRET: 2deec549-c51d-4120-9e97-6e7f5d578fb5
    volumes:
      - "./ui:/ui"
  api:
    build:
      context: api
    ports: ["8082:8082"]
    environment:
      KEYCLOAK_CLIENT_SECRET: ef94d40e-887f-41f3-8547-67b214b84ef2
  mail:
    image: mailhog/mailhog
    ports:
    - "8025:8025"
    - "1025:1025"
